### ISSUE TITLE
File jaspersoft_webserviceds_v1.5.zip does not exist on cloudfround domain.

### ISSUE THREAD

**Issue by georgezim85** [retrievercommunications/docker-jasperserver#28]
jasperserver    | --2019-01-05 19:12:14--  https://d2553lapexsdrl.cloudfront.net/sites/default/files/releases/jaspersoft_webserviceds_v1.5.zip
jasperserver    | Resolving d2553lapexsdrl.cloudfront.net (d2553lapexsdrl.cloudfront.net)... failed: Name or service not known.
jasperserver    | wget: unable to resolve host address ‘d2553lapexsdrl.cloudfront.net’

**Comment by georgezim85** [comment]
I thing the file url address on entrypoint.sh must me replaced.

**Comment by grange74** [comment]
Thanks for reporting. 
TBH i can't remember why it was set to that URL in the first place.
We can either change the URL to:
https://community.jaspersoft.com/sites/default/files/releases/jaspersoft_webserviceds_v1.5.zip
or to download the zip file, check-in to this repo and add to container at build time. 
Do you have a preference?

**Comment by georgezim85** [comment]
Well, I can't start the JasperServer anymore...

I downloaded the zip file, and I added an ADD command on my Dockerfile, so made the necessary changes on my entrypoint.sh, but when I try to build, it shows another error:

root@70ffcf025cbc:/usr/local/tomcat/webapps/ROOT/WEB-INF/logs# cat jasperserver.log

2019-01-07 19:40:21,150 ERROR JNDIResourceProvider,localhost-startStop-1:75 - error closing context
javax.naming.OperationNotSupportedException: Context is read only
	at org.apache.naming.NamingContext.checkWritable(NamingContext.java:969)
	at org.apache.naming.NamingContext.close(NamingContext.java:767)
	at com.tonbeller.tbutils.res.JNDIResourceProvider.close(JNDIResourceProvider.java:72)
	at com.tonbeller.tbutils.res.CompositeResourceProvider.close(CompositeResourceProvider.java:56)
	at com.tonbeller.tbutils.res.ResourcesFactory.initialize(ResourcesFactory.java:163)
	at com.tonbeller.tbutils.res.ResourcesFactory.<init>(ResourcesFactory.java:92)
	at com.tonbeller.tbutils.res.ResourcesFactory.<clinit>(ResourcesFactory.java:89)
	at com.tonbeller.tbutils.res.ResourcesFactoryContextListener.contextInitialized(ResourcesFactoryContextListener.java:23)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5157)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5680)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1018)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:994)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1296)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2039)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)

Do you know how to make it work again?

Thanks for the attention

**Comment by grange74** [comment]
So if you test further and everything seems to be working fine then please submit a PR. I would tend to prefer to avoid downloading things during the bootstrap process.

**Comment by georgezim85** [comment]
It's working now after I updated my fork. Thank you very much.
